import { ProjectType } from "types/domain";

export const PROJECT_LIST: ProjectType[] = [
  {
    name: "공책",
    description: "📖 함께 사용하는 우리의 공간, 우리가 체크하자!",
    imageUrl: "/assets/gongcheck.png",
    pageUrl: "https://gongcheck.day",
    members: ["찬", "오리", "범고래", "쿼리치", "어썸오", "온스타", "코카콜라"],
  },
  {
    name: "꼭꼭",
    description: "약속을 전달해요, 꼭꼭으로 간편하게!",
    imageUrl: "/assets/kkogkkog.png",
    pageUrl: "https://kkogkkog.com",
    members: ["정", "아서", "레오", "루키", "준찌", "시지프"],
  },
  {
    name: "내편",
    description: "내 마음을 편지로, 내 편 💌 ",
    imageUrl: "/assets/naepyeon.png",
    pageUrl: "https://www.naepyeon.site",
    members: ["알렉스", "승팡", "제로", "케이", "소피아", "도리"],
  },
  {
    name: "달록",
    description: "달력이 기록을 공유할 때, 달록 🌙",
    imageUrl: "/assets/dallog.png",
    pageUrl: "https://dallog.me",
    members: ["매트", "리버", "후디", "파랑", "나인", "티거"],
  },
  {
    name: "레벨로그",
    description: "레벨 인터뷰의 모든 것, 레벨로그",
    imageUrl: "/assets/levellog.png",
    pageUrl: "https://levellog.app",
    members: ["로마", "페퍼", "알린", "릭", "이브", "결", "해리"],
  },
  {
    name: "모모",
    description: "한 눈에 참여하는 모임 서비스, '모두 모여라' 모모입니다.",
    imageUrl: "/assets/moyeora.png",
    pageUrl: "https://moyeora.site",
    members: ["이프", "렉스", "라쿤", "유콩", "하리", "유세지"],
  },
  {
    name: "스모디",
    description: "작심삼일에 지쳤을 때.. Three More Days, 스모디",
    imageUrl: "/assets/smody.png",
    pageUrl: "https://www.smody.co.kr/home",
    members: ["알파", "토닉", "조조그린", "더즈", "빅터", "마르코", "우연"],
  },
  {
    name: "줍줍",
    description: "🐹 사라지는 Slack 메시지, 우리가 주워줄게!",
    imageUrl: "/assets/jupjup.png",
    pageUrl: "https://jupjup.site",
    members: ["봄", "써머", "리차드", "연로그", "꼬재", "호프"],
  },
  {
    name: "터놓고",
    description: "면담은 찐하게, 예약은 손쉽게! 올인원 면담 예약 서비스 💖",
    imageUrl: "/assets/ternoko.png",
    pageUrl: "https://ternoko.site",
    members: ["열음", "애쉬", "앤지", "수달", "바니", "아놀드", "록바"],
  },
  {
    name: "공식",
    description: "공식(공유해줘 너의 지식) : 우테코 크루들을 위한 질문 게시판",
    imageUrl: "/assets/gongseek.png",
    pageUrl: "https://gongseek.site",
    members: ["레넌", "기론", "주디", "슬로", "샐리", "자스민"],
  },
  {
    name: "땡쿠",
    description: "당신의 마음을 전달하세요, 땡쿠 💌",
    imageUrl: "/assets/thankoo.png",
    pageUrl: "https://thankoo.co.kr",
    members: ["스컬", "라라", "호호", "후니", "비녀", "후이"],
  },
  {
    name: "모락",
    description: "😄 모락: 모임을 즐겁게, 편하게!",
    imageUrl: "/assets/morak.png",
    pageUrl: "https://mo-rak.com",
    members: ["엘리", "차리", "에덴", "배카라", "앨버", "위니"],
  },
  {
    name: "모아모아",
    description: "🪐 스터디를 모아모아 🪐",
    imageUrl: "/assets/moamoa.png",
    pageUrl: "https://moamoa.space",
    members: ["그린론", "짱구", "디우", "베루스", "병민", "태태"],
  },
  {
    name: "속닥속닥",
    description:
      "말하기 힘들었던 이야기들을 익명의 힘을 빌려 자유롭게 꺼낼 수 있는 우리만의 대나무숲, 속닥속닥",
    imageUrl: "/assets/sokdak.png",
    pageUrl: "https://sokdaksokdak.com",
    members: ["크리스", "조시", "헌치", "토르", "이스트", "동키콩", "무비"],
  },
  {
    name: "체크메이트",
    description: "주제만 정해주세요. 출첵은 제가할게요!",
    imageUrl: "/assets/checkmate.png",
    pageUrl: "https://checkmate.today",
    members: ["쿤", "필즈", "썬", "아스피", "포키", "밧드", "우디"],
  },
  {
    name: "티타임",
    description: "서로를 채워주는 시간, 티타임",
    imageUrl: "/assets/teatime.png",
    pageUrl: "https://teatime.pe.kr/",
    members: ["아키", "야호", "잉", "마루", "안", "코이"],
  },
  {
    name: "회고덕",
    description: "✏️ 함께 성장하는 회고 플랫폼, 회고덕",
    imageUrl: "/assets/ducks.png",
    pageUrl: "https://ducks.kr",
    members: ["루나", "판다", "소주캉", "아리", "콤피", "돔하디"],
  },
  {
    name: "F12",
    description: "개발자의 모든 도구, F12 💻",
    imageUrl: "/assets/f12.png",
    pageUrl: "https://f12.app",
    members: ["칙촉", "클레이", "오찌", "티키", "코린", "블링", "민초"],
  },
];
